### ISSUE TITLE
video support

### ISSUE THREAD

**Issue by coronoal** [andfaraway/live_photo_maker#1]
Can it be supported to transfer a picture file as the cover and a video file as the content?
```
var result = await LivePhotoMaker.create(
        imagePath: '',
        videoPath: '',
        width: content.width,
        height: content.height);
```

**Comment by andfaraway** [comment]
Yeah, thank you for your suggestion. I will add this feature later.

**Comment by andfaraway** [comment]
video support is well @coronoal
